level_city_map =[
'                                                                                                  ',
'                                                                                                  ',
'                                                                          BB   B  XX         XXXXX',
'                                                                   S  B           XX         XXXXX',
'                                                                   S              XXBB  BBBBBXXXXX',
'                                                                   S              XXFF  FFFFFXXXXX',
'                                                                   SBB            XX         XXXXX',
'                                                                       S      S   XXBB  B  BBXXXXX',
'                                                                       SBB    S   XXFFFFF  FFXXXXX',
'                                                            FF    R               XX         XXXXX',
'                                                          F    XXXXXXX       B    XX   BB  BBXXXXX',
'                                                      FF       XTXTXTX            XX   FFFFFFXXXXX',
'                                             FFFF         F    XXXXXXX            XX         XXXXX',
' P     RR    R   C  FF           F         R      R            XTXTXTX         BB XXB    BBBBXXXXX',
'XXXXXXXXXXXXXXXXXX          FF          XXXXXXXXXXXXXX  BBB    XXXXXXX            XXFFF  FFFFFFOOO',
'XXTTTXXXTTXXXTTTXX      F          BB   XTXTTXTTXTTXTX         XTXTXTX     BB     XX            EO',
'XXXXXXXXXXXXXXXXXX                      XXXXXXXXXXXXXX         XXXXXXX            XXXXXXXXXXXXXOOO',
'XXTTTXXXTTXXXTTTXX                      XTXTTXTTXTTXTX         XTXTXTXBBB         XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXXXXXXXSSSSSSSSSXXXXXXXSSSSSSSSSSSSXXXXXXXXXXXXXXXX',
'XXTTTXXXTTXXXTTTXXXXXXXXXXXXXXXXXXXXXXXXXTXTTXTTXTTXTXXXXXXXXXXXTXTXTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]