level_tutorial_map = [
'                                   B    B                                       ',
'                               B   F    F                                       ',
'                               F             B   B   TTT                        ',
'                           B                 F   F   XXX  TT                    ',
'                           F                         XXX     TT                 ',
'                        B                            XXX         TT             ',
'                     TTTTTTTTTSTTT   B               XXX            TT          ',
'                     XXXXXXXXXXXXX   F   B           XXX                TT    E ',
'                                         F           XXX                    TTTT',
'                                             B       XXX                        ',
'                        TTT     TTT          F       XXX                        ',
'              TTTT  TT      TT      TT   TTTT   B    XXX                        ',
'   P TTTTTSTTTXXXX          XX           XXXXTTTTTTTTXXX                        ',
' TTTTXXXXXXXXXXXXXSSSSSSSSSSXXSSSSSSSSSSSXXXXXXXXXXXXXXXSSSSSSSSSSSSSSSSSSSSSSSS',
' XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
' XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]
