level_city_map =[
'                                                                                                     ',
'                                                                                                     ',
'                                                                          B  BB   B  LK         LXXXX',
'                                                                      S              XX         XXXXX',
'                                                                      S              XXBB  BBBBBXXXXX',
'                                                                      S              XXFF  FFFFFXXXXX',
'                                                                      SBB            XX         XXXXX',
'                                                                          S      S   XXBB  B  BBXXXXX',
'                                                                          SBB    S   XXFFFFF  FFXXXXX',
'                                                               FF    R               XX         XXXXX',
'                                                             F    LXXXXXK       B    XX   BB  BBXXXXX',
'                                                         FF       XTXTXTX            XX   FFFFFFXXXXX',
'                                                FFFF         F    XXXXXXX            XX         XXXXX',
'MMM  P    RR    R      FF           F         R      R            XTXTXTX         BB XXB    BBBBXXXXX',
'LXXXXXXXXXXXXXXXXXXXK          FF          LXXXXXXXXXXXXK  BBB    XXXXXXX            XXFFF  FFFFFFOOO',
'XXTTTXXTTXXXTTXXTTTXX      F          BB   XTXTTXTTXTTXTX         XTXTXTX     BB     XX            EO',
'XXXXXXXXXXXXXXXXXXXXX                      XXXXXXXXXXXXXX         XXXXXXX            XXXXXXXXXXXXXOOO',
'XXTTTXXTTXXXTTXXTTTXX                      XTXTTXTTXTTXTX         XTXTXTXBBB         XXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXSSSSSSSSSSSSSSSSSSSSSSXXXXXXXXXXXXXXSSSSSSSSSXXXXXXXSSSSSSSSSSSSXXXXXXXXXXXXXXXX',
'XXTTTXXTTXXXTTXXTTTXXXXXXXXXXXXXXXXXXXXXXXXXTXTTXTTXTTXTXXXXXXXXXXXTXTXTXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]