level_tutorial_map = [ 
'                                           BBB                                            ',
'                                      BBB  FFF  B                                         ',
'                                      FFF       F  BB  BB   TTT                           ',
'                                  B                FF  FF   XXX  FF                       ',
'                                  F                         XXX     FF                    ',
'                               B                            XXX         FF                ',
'                            TTTTTTTTTSTTT   BB              XXX             FF            ',
'                            XXXXXXXXXXXXX   FF  BB          XXX                FF    EOOOO',
'                                                FF          XXX                    TTTTTTT',
'                                                    B       XXX                    XXXXXXX',
'                             FFF      FFF           F       XXX                    XXXXXXX',
'                    TTT  FF       TT       FF   TTT    B    XXX                    XXXXXXX',
'   P        TTTTSTTTXXX           XX            XXXTTTTTTTTTXXX                    XXXXXXX',
'TTTTTTTTTTTTXXXXXXXXXXXSSSSSSSSSSSXXSSSSSSSSSSSSXXXXXXXXXXXXXXXSSSSSSSSSSSSSSSSSSSSXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]
