level_tutorial_map = [ 
'                                           BBB                                            ',
'                                      BB   FFF  B                                         ',
'                                      FF        F  BB  BB   TTT                           ',
'                                  B                FF  FF   XXX  FF                       ',
'                                  F                         XXX     FF                    ',
'                               B                            XXX         FF                ',
'                            TTTTTTTTTSTTT   BB              XXX             FF            ',
'                            XXXXXXXXXXXXX   FF  BB          XXX                FF    IOOOO',
'                                                FF          XXX                    TTTTTTT',
'                                                    B       XXX                    XXXXXXX',
'                             FFF         MMM        F       XXX                    XXXXXXX',
'                    TTT  FF       TT            TTT    B    XXX                    XXXXXXX',
'   P        TTTTSTTTXXX           XX            XXXTTTTTTTTTXXX                    XXXXXXX',
'TTTTTTTTTTTTXXXXXXXXXXXSSSSSSSSSSSXXSSSSSSSSSSSSXXXXXXXXXXXXXXXSSSSSSSSSSSSSSSSSSSSXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]
